const words = [
  "Synergy",
  "Think outside the box",
  "Take it offline",
  "Circle back",
  "Low - hanging fruit",
  "At the end of the day",
  "The Cloud",
  "To not know what you don’t know",
  "Big Data",
  "Move the needle",
  "Leverage",
  "Agile",
  "Best Practice",
  "Digital transformation",
  "Deep dive",
  "Bandwidth",
  "Customer journey",
  "Moving forward",
  "Next level",
  "Reach out",
  "Touch base",
  "Wheelhouse",
  "Disruptor",
  "Alignment",
  "Right",
  "Bottom line",
  "Acronyms",
  "Disruptive",
  "Value",
  "Ping",
  "Lean, and lean -in",
  "Paradigm",
  "Ideate",
  "A slight ask",
  "Learnings",
  "Holistic",
  "Culture",
  "Thought leader",
  "Content",
  "Growth hacking",
  "Buy -in",
  "Pain point",
  "Swimlane",
  "Best in class",
  "Game-changer",
  "Teamwork",
  "Next - gen",
  "Hard stop",
  "ROI",
  "IoT",
  "Innovative",
  "Influencer",
  "Single pane of glass",
  "Customer - centric",
  "All hands on deck",
  "Net - net",
  "Put a pin in it",
  "Stakeholders",
  "Strategic",
  "Metrics",
  "Machine Learning",
  "Pivot",
  "On the same page",
  "Advertainment",
  "Collaboration",
  "Intelligence",
  "Automation",
  "Blockchain",
  "Intuitive",
  "Analytics",
  "Platform",
  "Unpack",
  "Giving 110 %",
  "Table stakes",
  "Let's table it for later",
  "Quick win",
  "Onboarding",
  "Scrum",
  "Boil the ocean",
  "Story",
  "On your plate",
  "30, 000 ft.view",
  "Core competency",
  "Rockstar",
  "Keep you in the loop",
  "Freemium",
  "Blue sky",
  "Integration",
  "Engagement",
  "Actionable",
  "Efficiency",
  "Socialize",
  "Diversity",
  "Verticals",
  "Bio -break",
  "Bleeding edge",
  "Optimize",
  "Scalable",
  "Organic",
  "Omni - channel",
  "Empower",
  "Win - win",
  "Optics",
  "DevOps",
  "Data - driven",
  "In the weeds",
  "Double click",
  "On your radar",
  "Ducks in a row",
  "Drill down",
  "Fast follower",
  "Top of mind",
  "KPI",
  "ASAP",
  "Giving back your time",
  "Per my last email",
  "FYI",
]

export default words
